# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = uwsm-app -- swww-daemon
exec-once = swww img ~/.config/omarchy/current/background
# exec-once = uwsm-app -- elephant
# exec-once = omarchy-restart-walker
