# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

unbind = SUPER, S
unbind = SUPER, F
unbind = SUPER, M
unbind = SUPER, D
unbind = SUPER ALT, S
unbind = SUPER CTRL, L
unbind = SUPER CTRL, SPACE
unbind = SUPER ALT, SPACE
unbind = SUPER, SPACE

# Apps
bindd = SUPER, RETURN, Launch Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Launch Alternate Terminal, exec, alacritty
bindd = SUPER, F, Launch File Manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, B, Launch Browser, exec, $browser --disable-gpu
bindd = SUPER SHIFT, B, Launch Browser (private), exec, $browser --private --disable-gpu
bindd = SUPER ALT, B, Launch Alternate Browser, exec, uwsm-app -- chromium --disable-gpu
bindd = SUPER SHIFT ALT, B, Launch Alternate Browser (private), exec, uwsm-app -- chromium --incognito --disable-gpu
bindd = SUPER, M, Launch Spotify, exec, omarchy-launch-or-focus spotify
bindd = SUPER, N, Launch Editor, exec, omarchy-launch-editor
bindd = SUPER, Z, Launch Yazi, exec, $terminal -e yazi
# bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
# bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"

# Wallpaper & Theming
bindd = SUPER ALT, T, Wallpaper Menu, exec, walset.sh
bindd = SUPER CTRL, SPACE, Next Wallpaper, exec, change-wallpaper.sh

# Audio Switch
bindd = SUPER SHIFT, A, Audio Switch Menu, exec, audioswitch.sh

# Utility Bindings
bindd = SUPER SHIFT, F, Fullscreen, fullscreen, 0
bindd = SUPER, L, Lock Screen, exec, omarchy-lock-screen
bindd = SUPER SHIFT, L, Suspend, exec, systemctl suspend
bindd = ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER, SPACE, Applications, exec, omarchy-launch-walker

# Special Workspaces
bind = ALT, S, togglespecialworkspace, scratchpad
bind = ALT, P, togglespecialworkspace, productivity

# Move Windows to Special Workspaces
bind = ALT SHIFT, S, movetoworkspacesilent, special:scratchpad
bind = ALT SHIFT, P, movetoworkspacesilent, special:productivity

