# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

unbind = SUPER, F
unbind = SUPER, M
unbind = SUPER, D
unbind = SUPER ALT, S
unbind = SUPER CTRL, SPACE
unbind = SUPER ALT, SPACE
unbind = SUPER, SPACE

# Apps
bindd = SUPER, RETURN, Launch Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Launch Alternate Terminal, exec, alacritty
bindd = SUPER, F, Launch File Manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, B, Launch Browser, exec, $browser --disable-gpu
bindd = SUPER SHIFT, B, Launch Browser (private), exec, $browser --private --disable-gpu
bindd = SUPER ALT, B, Launch Alternate Browser, exec, uwsm-app -- firefox --disable-gpu
bindd = SUPER SHIFT ALT, B, Launch Alternate Browser (private), exec, uwsm-app -- firefox --private-window --disable-gpu
bindd = SUPER, M, Launch Spotify, exec, omarchy-launch-or-focus spotify
bindd = SUPER, N, Launch Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, T, Launch Activity Monitor, exec, $terminal -e btop
bindd = SUPER, C, Launch VS Code, exec, code
# bindd = SUPER, D, Docker, exec, $terminal -e lazydocker
# bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus "^obsidian$" "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"

# Wallpaper & Theming
bindd = SUPER ALT, T, Wallpaper Menu, exec, walset.sh
bindd = SUPER CTRL, SPACE, Next Wallpaper, exec, change-wallpaper.sh

bindd = SUPER SHIFT, F, Fullscreen, fullscreen, 0
bindd = SUPER, L, Lock Screen, exec, omarchy-lock-screen
bindd = SUPER SHIFT, L, Suspend, exec, systemctl suspend
bindd = SUPER SHIFT, period, Next Workspace, workspace, +1
bindd = SUPER SHIFT, comma, Prev Workspace, workspace, -1
bindd = ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER, SPACE, Applications, exec, omarchy-menu apps
bindd = SUPER, I, Wifi, exec, omarchy-launch-wifi
bindd = SUPER SHIFT, I, Bluetooth, exec, omarchy-launch-or-focus-tui bluetui
bindd = SUPER SHIFT, S, Move window to scratchpad, movetoworkspacesilent, special:scratchpad
#bind = SUPER, SLASH, hyprexpo:expo, toggle

