# Application bindings
$terminal = uwsm-app -- xdg-terminal-exec
$browser = omarchy-launch-browser

unbind = SUPER, S
unbind = SUPER, F
unbind = SUPER, M
unbind = SUPER, D
unbind = SUPER ALT, S
unbind = SUPER ALT, F
unbind = SUPER CTRL, C
unbind = SUPER CTRL, L
unbind = SUPER CTRL, BACKSPACE
unbind = SUPER CTRL, SPACE
unbind = SUPER ALT, SPACE
unbind = SUPER, SPACE
unbind = SUPER SHIFT CTRL, SPACE
unbind = SUPER SHIFT, RETURN

# Apps
bindd = SUPER, RETURN, Launch Terminal, exec, $terminal --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER ALT, RETURN, Launch Alternate Terminal, exec, alacritty
bindd = SUPER, F, Launch File Manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER, B, Launch Browser, exec, $browser --disable-gpu
bindd = SUPER SHIFT, B, Launch Browser (private), exec, $browser --private --disable-gpu
bindd = SUPER ALT, B, Launch Alternate Browser, exec, uwsm-app -- brave --disable-gpu
bindd = SUPER SHIFT ALT, B, Launch Alternate Browser (private), exec, uwsm-app -- brave --incognito --disable-gpu
bindd = SUPER, M, Launch Spotify, exec, uwsm-app -- spotify
bindd = SUPER, N, Launch Editor, exec, omarchy-launch-editor
bindd = SUPER, Z, Launch Yazi, exec, $terminal -e yazi

# Wallpaper & Theming
bindd = SUPER SHIFT, T, Wallpaper Menu, exec, walset.sh
bindd = SUPER CTRL, SPACE, Next Wallpaper, exec, change-wallpaper.sh

# Audio Switch
bindd = SUPER SHIFT, A, Audio Switch Menu, exec, audioswitch.sh

# Utility Bindings
bindd = SUPER SHIFT, F, Fullscreen, fullscreen, 1
bindd = SUPER, L, Lock Screen, exec, omarchy-lock-screen
bindd = ALT, L, Screensaver, exec, omarchy-launch-screensaver
bindd = SUPER SHIFT, L, Suspend, exec, systemctl suspend
bindd = ALT, SPACE, Omarchy menu, exec, omarchy-menu
bindd = SUPER, SPACE, Applications, exec, omarchy-launch-walker
bindd = CTRL SHIFT, M, Word Definition, exec, define.sh

# Special Workspaces
bind = ALT, S, togglespecialworkspace, scratchpad
bind = ALT, P, togglespecialworkspace, productivity
bind = ALT, M, togglespecialworkspace, music

# Move Windows to Special Workspaces
bind = ALT SHIFT, S, movetoworkspacesilent, special:scratchpad
bind = ALT SHIFT, P, movetoworkspacesilent, special:productivity
bind = ALT SHIFT, M, movetoworkspacesilent, special:music

