# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {

    border_size = 1

    # No gaps between windows
    gaps_in = 3
    gaps_out = 5

    col.active_border = $on_background
    col.inactive_border = $on_primary

    resize_on_border = true

    # Use master layout instead of dwindle
    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 5
    active_opacity = 0.95
    inactive_opacity = 0.8

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 5
        passes = 2
        vibrancy = 0.2
    }

    shadow {
        enabled = false
      }
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

group {
    col.border_active = $on_background
    col.border_inactive = $on_primary
    auto_group = true

    groupbar {
        # rounding = 10
        font_family = FiraCode Nerd Font Mono
        font_size = 12
        height = 30
        text_offset = -1
        indicator_gap = 1
        indicator_height = 1
        col.active = $primary
        col.inactive = $on_primary
        text_color = $primary
        text_color_inactive = $tertiary
        gaps_in = 0
        gaps_out = 0
        # font_weight_active = bold
        # font_weight_inactive = normal
    }
}

misc {
    vfr = true
}

layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.3, match:namespace waybar
#layerrule = blur, walker
layerrule = animation cubicz, match:namespace walker

