# : Manager [[[

[manager]
cwd = { fg = "#ecdfe5" }

# Tab
tab_active = { fg = "#4c1f49", bg = "#f1b3e6", bold = true }
tab_inactive = { fg = "#ffd7f5", bg = "#330832" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#ff8b6b", bg = "#ff8b6b" }
marker_cut = { fg = "#ffdbd1", bg = "#ffdbd1" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#f5b8a7", bg = "#f5b8a7" }

# Count
count_copied = { fg = "#321208", bg = "#ffdbd1" }
count_cut = { fg = "#321208", bg = "#ffdbd1" }
count_selected = { fg = "#4c1f49", bg = "#f5b8a7" }

# Border
border_symbol = "│"
border_style  = { fg = "#f1b3e6" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#4c1f49", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#f1b3e6", fg = "#4c1f49", bold = true }
normal_alt  = { bg = "#4e444b", fg = "#d1c2cb" }

# Select mode
select_main = { bg = "#dabfd2", fg = "#3d2b3a", bold = true }
select_alt  = { bg = "#4e444b", fg = "#d1c2cb" }

# Unset mode
unset_main = { bg = "#f5b8a7", fg = "#4c261b", bold = true }
unset_alt  = { bg = "#4e444b", fg = "#d1c2cb" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#f1b3e6", bg = "#3e373c" }
progress_error = { fg = "#ffb4ab", bg = "#3e373c" }

# Permissions
permissions_t = { fg = "#a25e8e" }
permissions_w = { fg = "#e5491e" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#ff6338" }
permissions_s = { fg = "#ff3ecf" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#f1b3e6" }
active = { fg = "#f5b8a7", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#f1b3e6" }
value = { fg = "#ecdfe5" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#f1b3e6", bg = "#4c1f49" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#f1b3e6" }
title = {}
hovered = { fg = "#ffdbd1", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#3e373c" }
cand = { fg = "#f1b3e6" }
rest = { fg = "#4c1f49" }
desc = { fg = "#ecdfe5" }
separator = " ▶ "
separator_style = { fg = "#ecdfe5" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#ecdfe5" }
run = { fg = "#ecdfe5" }
footer = { fg = "#3d2b3a", bg = "#dabfd2" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#f5b8a7" }
title_warn = { fg = "#f1b3e6" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#ecdfe5" },
    { name = "*/", fg = "#f1b3e6" },
]

# : ]]]

