# : Manager [[[

[manager]
cwd = { fg = "#e2e2e9" }

# Tab
tab_active = { fg = "#172e60", bg = "#b1c5ff", bold = true }
tab_inactive = { fg = "#dae2ff", bg = "#001847" }
tab_width = 1

# Find
find_keyword = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied = { fg = "#fc73ea", bg = "#fc73ea" }
marker_cut = { fg = "#fed7f9", bg = "#fed7f9" }
marker_marked = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e1bbdd", bg = "#e1bbdd" }

# Count
count_copied = { fg = "#2a122c", bg = "#fed7f9" }
count_cut = { fg = "#2a122c", bg = "#fed7f9" }
count_selected = { fg = "#172e60", bg = "#e1bbdd" }

# Border
border_symbol = "│"
border_style  = { fg = "#b1c5ff" }

# : ]]]


# : Status [[[

[status]
separator_open = "🭁"
separator_close = "🭠"
separator_style = { bg = "#172e60", fg = "#F4A261" }

[mode]
# Mode
normal_main = { bg = "#b1c5ff", fg = "#172e60", bold = true }
normal_alt  = { bg = "#44464f", fg = "#c5c6d0" }

# Select mode
select_main = { bg = "#c0c6dd", fg = "#2a3042", bold = true }
select_alt  = { bg = "#44464f", fg = "#c5c6d0" }

# Unset mode
unset_main = { bg = "#e1bbdd", fg = "#412742", bold = true }
unset_alt  = { bg = "#44464f", fg = "#c5c6d0" }

# Progress
progress_label = { bold = true }
progress_normal = { fg = "#b1c5ff", bg = "#38393f" }
progress_error = { fg = "#ffb4ab", bg = "#38393f" }

# Permissions
permissions_t = { fg = "#5d6ca7" }
permissions_w = { fg = "#b251a8" }
permissions_x = { fg = "#ff2b12" }
permissions_r = { fg = "#fa42e3" }
permissions_s = { fg = "#416aff" }

# : ]]]


# : Select [[[

[select]
border = { fg = "#b1c5ff" }
active = { fg = "#e1bbdd", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#b1c5ff" }
value = { fg = "#e2e2e9" }

# : ]]]


# : Completion [[[

[completion]
border = { fg = "#b1c5ff", bg = "#172e60" }

# : ]]]


# : Tasks [[[

[tasks]
border = { fg = "#b1c5ff" }
title = {}
hovered = { fg = "#fed7f9", underline = true }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#38393f" }
cand = { fg = "#b1c5ff" }
rest = { fg = "#172e60" }
desc = { fg = "#e2e2e9" }
separator = " ▶ "
separator_style = { fg = "#e2e2e9" }

# : ]]]


# : Help [[[

[help]
on = { fg = "#e2e2e9" }
run = { fg = "#e2e2e9" }
footer = { fg = "#2a3042", bg = "#c0c6dd" }

# : ]]]


# : Notify [[[

[notify]
title_info = { fg = "#e1bbdd" }
title_warn = { fg = "#b1c5ff" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { name = "*", fg = "#e2e2e9" },
    { name = "*/", fg = "#b1c5ff" },
]

# : ]]]

