[colors.primary]
background = '#1a110e'
foreground = '#f1dfd9'
 
[colors.cursor]
text = '#f1dfd9'
cursor = '#d8c2bb' 
 
[colors.vi_mode_cursor]
text = '#1a110e'
cursor = '#ffb59a' 
 
[colors.search.matches]
foreground = '#53433e' 
background = '#d5c68e' 
 
[colors.search.focused_match]
foreground = '#53433e' 
background = '#ffb59a' 
 
[colors.footer_bar]
foreground = '#53433e' 
background = '#f1dfd9' 
 
[colors.hints.start]
foreground = '#53433e' 
background = '#e7beaf' 
 
[colors.hints.end]
foreground = '#53433e' 
background = '#e7beaf' 
 
[colors.selection]
text = '#1a110e'
background = '#ffb59a'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#ffb59a' 
yellow = '#8f4c33' 
blue = '#ffb59a' 
magenta = '#d5c68e' 
cyan = '#e7beaf' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
