[colors.primary]
background = '#181216'
foreground = '#ecdfe5'
 
[colors.cursor]
text = '#ecdfe5'
cursor = '#d2c2cb' 
 
[colors.vi_mode_cursor]
text = '#181216'
cursor = '#f3b2e3' 
 
[colors.search.matches]
foreground = '#4e444b' 
background = '#f5b9a4' 
 
[colors.search.focused_match]
foreground = '#4e444b' 
background = '#f3b2e3' 
 
[colors.footer_bar]
foreground = '#4e444b' 
background = '#ecdfe5' 
 
[colors.hints.start]
foreground = '#4e444b' 
background = '#dbbed1' 
 
[colors.hints.end]
foreground = '#4e444b' 
background = '#dbbed1' 
 
[colors.selection]
text = '#181216'
background = '#f3b2e3'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#f3b2e3' 
yellow = '#814c77' 
blue = '#f3b2e3' 
magenta = '#f5b9a4' 
cyan = '#dbbed1' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
