font=FiraCode Nerd Font 12

background-color=#{{colors.background.default.hex_stripped}}
text-color=#{{colors.primary_fixed_dim.default.hex_stripped}}
width=420
height=110
padding=10
#margin=10,10,0,0
outer-margin=20
progress-color=over #{{colors.background.default.hex_stripped}}
layer=overlay

border-size=2
border-radius=10
border-color=#{{colors.primary_fixed_dim.default.hex_stripped}}

default-timeout=5000

[urgency=high]

ignore-timeout=1

